---
title: "Getting and Cleaning Project Codebook"
author: "Bill Holst"
date: "11/12/2015"
---

## Project Description

Process a set of data, collected from Samsung Galaxy S smartphone about wearable computing, creating a "tidy" data set. 

##Study design and data processing

Use a series of R functions in an R script called run_analysis to download, clean, and process the data

###Collection of the raw data
Original data was collected from Samsung Galaxy 5 smartphone and consists of 561 variables measured by the phone of 30 subjects.  The variables are in both a training and test set.  Data are available in a zip file from

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 

###Notes on the original (raw) data 

The original description of the data collected is at 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

In addtion to the training and test variable files, there is a subject file, a feature description file and two (training and test) activity files.  

##Creating the tidy datafile

- download and unzip data with the unzip() function
- load each of the files into memory with read.table() function
- establish the eventual column headers from the features data, giving a set, featureLabels, of feature labels
- identify the features that are either 'mean' or 'std', creating a vector featuresToRead to filter the variables

###Cleaning of the data

The cleaning of the data consists of the following:

- clean up the feature labels with some simple substitution, e.g. remove "()"
- filter the training and test sets by selection only columns in the featuresToRead vector
- column bind the subject, activity, and filtered variables with the cbind() function for both training and test data
- row bind the two datasets from the prior operation
- add the column headers from the FeatureLabels vector
- substitute the description of the activity for the activity code
- create a new dataset with the means of the 79 variables, grouped by subject and activity
- write the results to a file called "combinedMeansTidy.txt"

##Description of the variables in the combinedMeansTidy.txt file


 "Subject" - number of the subject participant
 "Activity" - activity description, from one of six:
 - 1            WALKING
 - 2   WALKING_UPSTAIRS
 - 3 WALKING_DOWNSTAIRS
 - 4            SITTING
 - 5           STANDING
 - 6             LAYING
  
 The remaining varialble means:
 
 [3] "tBodyAcc- Mean -X"               "tBodyAcc- Mean -Y"              
 [5] "tBodyAcc- Mean -Z"               "tBodyAcc- StDev -X"             
 [7] "tBodyAcc- StDev -Y"              "tBodyAcc- StDev -Z"             
 [9] "tGravityAcc- Mean -X"            "tGravityAcc- Mean -Y"           
[11] "tGravityAcc- Mean -Z"            "tGravityAcc- StDev -X"          
[13] "tGravityAcc- StDev -Y"           "tGravityAcc- StDev -Z"          
[15] "tBodyAccJerk- Mean -X"           "tBodyAccJerk- Mean -Y"          
[17] "tBodyAccJerk- Mean -Z"           "tBodyAccJerk- StDev -X"         
[19] "tBodyAccJerk- StDev -Y"          "tBodyAccJerk- StDev -Z"         
[21] "tBodyGyro- Mean -X"              "tBodyGyro- Mean -Y"             
[23] "tBodyGyro- Mean -Z"              "tBodyGyro- StDev -X"            
[25] "tBodyGyro- StDev -Y"             "tBodyGyro- StDev -Z"            
[27] "tBodyGyroJerk- Mean -X"          "tBodyGyroJerk- Mean -Y"         
[29] "tBodyGyroJerk- Mean -Z"          "tBodyGyroJerk- StDev -X"        
[31] "tBodyGyroJerk- StDev -Y"         "tBodyGyroJerk- StDev -Z"        
[33] "tBodyAccMag- Mean "              "tBodyAccMag- StDev "            
[35] "tGravityAccMag- Mean "           "tGravityAccMag- StDev "         
[37] "tBodyAccJerkMag- Mean "          "tBodyAccJerkMag- StDev "        
[39] "tBodyGyroMag- Mean "             "tBodyGyroMag- StDev "           
[41] "tBodyGyroJerkMag- Mean "         "tBodyGyroJerkMag- StDev "       
[43] "fBodyAcc- Mean -X"               "fBodyAcc- Mean -Y"              
[45] "fBodyAcc- Mean -Z"               "fBodyAcc- StDev -X"             
[47] "fBodyAcc- StDev -Y"              "fBodyAcc- StDev -Z"             
[49] "fBodyAcc- Mean Freq-X"           "fBodyAcc- Mean Freq-Y"          
[51] "fBodyAcc- Mean Freq-Z"           "fBodyAccJerk- Mean -X"          
[53] "fBodyAccJerk- Mean -Y"           "fBodyAccJerk- Mean -Z"          
[55] "fBodyAccJerk- StDev -X"          "fBodyAccJerk- StDev -Y"         
[57] "fBodyAccJerk- StDev -Z"          "fBodyAccJerk- Mean Freq-X"      
[59] "fBodyAccJerk- Mean Freq-Y"       "fBodyAccJerk- Mean Freq-Z"      
[61] "fBodyGyro- Mean -X"              "fBodyGyro- Mean -Y"             
[63] "fBodyGyro- Mean -Z"              "fBodyGyro- StDev -X"            
[65] "fBodyGyro- StDev -Y"             "fBodyGyro- StDev -Z"            
[67] "fBodyGyro- Mean Freq-X"          "fBodyGyro- Mean Freq-Y"         
[69] "fBodyGyro- Mean Freq-Z"          "fBodyAccMag- Mean "             
[71] "fBodyAccMag- StDev "             "fBodyAccMag- Mean Freq"         
[73] "fBodyBodyAccJerkMag- Mean "      "fBodyBodyAccJerkMag- StDev "    
[75] "fBodyBodyAccJerkMag- Mean Freq"  "fBodyBodyGyroMag- Mean "        
[77] "fBodyBodyGyroMag- StDev "        "fBodyBodyGyroMag- Mean Freq"    
[79] "fBodyBodyGyroJerkMag- Mean "     "fBodyBodyGyroJerkMag- StDev "   
[81] "fBodyBodyGyroJerkMag- Mean Freq"
> 
 - Summary of the data
 - Variables present in the dataset

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

###Variable 1 (repeat this section for all variables in the dataset)
Short description of what the variable describes.

Some information on the variable including:
 - Class of the variable
 - Unique values/levels of the variable
 - Unit of measurement (if no unit of measurement list this as well)
 - In case names follow some schema, describe how entries were constructed (for example time-body-gyroscope-z has 4 levels of descriptors. Describe these 4 levels). 

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

####Notes on variable 1:
If available, some additional notes on the variable not covered elsewehere. If no notes are present leave this section out.

##Sources
Sources you used if any, otherise leave out.

##Annex
If you used any code in the codebook that had the echo=FALSE attribute post this here (make sure you set the results parameter to 'hide' as you do not want the results to show again)
